<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE ROOT [ 
	<!ELEMENT ROOT (Machine+)>
	<!ELEMENT Machine (State+, Transition+, Push+, Check*, Act*, Device*, Comment*)>
		<!ATTLIST Machine Name ID #REQUIRED>
		<!ATTLIST Machine Info CDATA #IMPLIED>
	<!ELEMENT State (Comment*)>
		<!ATTLIST State Name ID #REQUIRED>
		<!ATTLIST State Enter CDATA #IMPLIED>
		<!ATTLIST State Exit CDATA #IMPLIED>
		<!ATTLIST State Info CDATA #IMPLIED>
	<!ELEMENT Transition (Comment*)>
		<!ATTLIST Transition From CDATA #REQUIRED>
		<!ATTLIST Transition To CDATA #REQUIRED>
		<!ATTLIST Transition Pushes CDATA #REQUIRED>
		<!ATTLIST Transition Checks CDATA #IMPLIED>
		<!ATTLIST Transition Acts CDATA #IMPLIED>
		<!ATTLIST Transition Info CDATA #IMPLIED>
	<!ELEMENT Check (Comment*)>
		<!ATTLIST Check Name ID #REQUIRED>
		<!ATTLIST Check Info CDATA #IMPLIED>
	<!ELEMENT Act (Comment*)>
		<!ATTLIST Act Name ID #REQUIRED>
		<!ATTLIST Act Info CDATA #IMPLIED>
	<!ELEMENT Push (Comment*)>
		<!ATTLIST Push Name ID #REQUIRED>
		<!ATTLIST Push Info CDATA #IMPLIED>
	<!ELEMENT Device (Comment*)>
		<!ATTLIST Device Name ID #REQUIRED>
		<!ATTLIST Device Type CDATA #REQUIRED>
		<!ATTLIST Device Info CDATA #IMPLIED>
	<!ELEMENT Comment (#PCDATA)>
		<!ATTLIST Comment Author CDATA #REQUIRED>
]>

<ROOT>
	<Machine Name="Dialog" Info="Show dialog">
		<State Name="First" Info="first status"><Comment Author="me">bugaga</Comment></State>
		<State Name="Last" Info="las status" />
		<State Name="Some" Enter="DoOne" Info="las status" />
		<Transition From="First" To="Last" Info="one trans" 
								Pushes="Start"
								Checks="IsAllGood IsUserHasRights IsNot"
								Acts="Make"
								/>
		<Transition From="Some" To="NoStat" Pushes="pushBad pushBad2" />
		<Push Name="Start" />
		<Push Name="Finish" />
		<Check Name="IsUserHasRights" Info="test user rights" />
		<Check Name="IsAllGood" />
		<Act Name="Make">
			<Comment Author="me">Big brown fox</Comment>
		</Act>
		<Act Name="DoOne" />
		<Act Name="DoTwo" />
		<Device Name="Connection" Type="SqlConnection" Info="conn to DB" />
	</Machine>
</ROOT>

